In [1]:

arr = [[[[0],[0],[0],[0],[0]]
        ,[[0],[0],[0],[0]],
        [[0,[0],[0],
          [0],[0]]]]]
        
print(arr)

[[[[0], [0], [0], [0], [0]], [[0], [0], [0], [0]], [[0, [0], [0], [0], [0]]]]]


In [9]:
import numpy as np
nda1 = np.zeros([2,3,2,3]) #2 dimension 2 ke ander 3(2 array 3 ke ander) uskay ander phr 3
print(nda1.shape)
nda1[1,1,0,1:3] =7 #1 array uthao phr 1 walay pr jao phr 0 uthao phr 1:3(3 wala nh hoga 2 tk jaiga)woh sara phr 7 ke barabar hoga

print(nda1)

(2, 3, 2, 3)
[[[[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 7. 7.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]]]


In [ ]:
np.abs? #to find something

In [ ]:
arr = np.zeros(4)
arr

In [ ]:
arr = arr + (-1)
arr



In [ ]:
np.abs(arr)

In [ ]:
np.where?

In [ ]:
arr = np.arange(1,11)
arr

In [ ]:
np.where(arr>5) #dhooond ke laiga jo zyada howa 5 se

In [ ]:
arr>5

In [ ]:
#mean
arr.mean()

In [ ]:
#cumsum   #1,1+2,3+3
arr.cumsum()

In [ ]:
#cumprod #same as cumsum but multiply karata ha
arr.cumprod()


In [ ]:
arr[arr > 5].sum()

In [ ]:
ar2 = arr>5
ar2.sum()

In [ ]:
any(arr==5)

In [ ]:
all(arr==2)

In [ ]:
all(arr<11)

In [ ]:
np.sort(arr) #sort the values of array

In [ ]:
arr = np.zeros(5)
arr

In [ ]:
np.unique(arr)

In [ ]:
arr4=1,2,3,4,5,6,7
np.save('bantoo baba',arr4)

In [ ]:
np.load('bantoo baba.npy')

In [14]:
import numpy as np
arr9=[1.2,2.4,3.7,4.3,-3]
np.ceil(arr9)

array([ 2.,  3.,  4.,  5., -3.])

In [15]:
np.floor(arr9)

array([ 1.,  2.,  3.,  4., -3.])

In [16]:
import numpy as np
np.random.seed(0)
perm =np.random.rand(3)
print(perm)

[0.5488135  0.71518937 0.60276338]


In [21]:
arr = np.arange(1,13)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [27]:
arr.reshape(((4,3)),order='F')

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [35]:
arr10 = np.arange(10,100,10)
arr10

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
a,b,c = np.split(arr10,[2,6])

In [42]:
a

array([10, 20])

In [43]:
b

array([30, 40, 50, 60])

In [44]:
c

array([70, 80, 90])

In [45]:
import numpy as np
arr = np.arange(1,11)
print(arr)

arr = np.split(arr,[2,4,6,8,10])
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[4])


[ 1  2  3  4  5  6  7  8  9 10]
[1 2]
[3 4]
[5 6]
[7 8]
[ 9 10]


# image to numpy

In [ ]:
import numpy as np
import matplotlib.pylab as plt
for i in range(1):
    im =plt.imread("image ki file")
    print((type)im)
    print(m.shape)
    


In [ ]:
#20 photos uthani hain unko resize krni hain 512,512,3 mein phr 1 array mein 20 element banainay aur unko numpy mein convert krna ha