In [1]:
import numpy as np
text= "You’re going to learn by doingYoull read a chapter, then practice with the exercises. That way, the knowledge gets embedded in your memory so you don forget it. Instant feedback corrects your mistakes like a one-on-one teacher. I’ve done my best to write each chapter so it’s easy for anyone to understand, but it’s the exercises that are going to turn you into a real Python coder. Cognitive research shows that reading alone doesn’t buy you much longterm retention. Even if you read a book a second or even a third time, things won’t improve much, according to research. And forget highlighting or underlining. Marking up a book gives us the illusion that we’re engaging with the material, but studies show that it’s an exercise in self-deception. It doesn’t matter how much yellow you paint on the pages, or how many times you review the highlighted material. By the time you get to Chapter 50, you’ll have forgotten most of what you highlighted in Chapter 1. This all changes if you read less and do more—if you read a short passage and then immediately put it into practice. Washington University researchers say that being asked to retrieve information increases long-term retention by four ******ebook converter DEMO Watermarks*******"
text = np.array(text.split())
print(text[:10])
print(type(text))
print(len(text))


['You’re' 'going' 'to' 'learn' 'by' 'doingYoull' 'read' 'a' 'chapter,'
 'then']
<class 'numpy.ndarray'>
207


In [ ]:
d3 = np.array([[[[1,1],[1,2],[3,3],[4,3]
                ,[5,5],[4,3],[0,0],[9,8]
                ,[0,1],[0,2],[0,3],[0,4]],[[1,1],[1,2],[3,3],[4,3]
                ,[5,5],[4,3],[0,0],[9,8]
                ,[0,1],[0,2],[0,3],[0,4]]],[[[1,1],[1,2],[3,3],[4,3]
                ,[5,5],[4,3],[0,0],[9,8]
                ,[0,1],[0,2],[0,3],[0,4]],[[1,1],[1,2],[3,3],[4,3]
                ,[5,5],[4,3],[0,0],[9,8]
                ,[0,1],[0,2],[0,3],[0,4]]],[[[1,1],[1,2],[3,3],[4,3]
                ,[5,5],[4,3],[0,0],[9,8]
                ,[0,1],[0,2],[0,3],[0,4]],[[1,1],[1,2],[3,3],[4,3]
                ,[5,5],[4,3],[0,0],[9,8]
                ,[0,1],[0,2],[0,3],[0,4]]]])
print(d3)
print(d3)
print(d3.size)
print(d3.ndim)
print(d3.shape)

In [ ]:
print(d3[0,1])

In [ ]:
d3[:2,:1,:1]

In [ ]:
#vectorization
arr = np.array([12,-45,67,89,34,-2,6,-7,8])
print(arr * 6) #scaler operation will propagate
print(arr[:3] * 6)
#in list we cannot do that


In [2]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])

c = a + b
print(c)
#broadcasting (row size should be same)
d = np.array([4,3,2])
print("d array", d)
print(c.shape,d.shape)
print(c+d)

#comparing array will return boolean array
#we can use boolean array for filtering data
boolean_e = (a == b)
c = a + b
print(c)
print(boolean_e)
#filtering data using boolean array
cfilter = c [boolean_e]   #true walay ayengay false walay nh
print(cfilter)
#direct filter instead of boolean array
cfilter =  c[c < 15]
print(cfilter)


[[ 8 10 12]
 [14 16 18]]
d array [4 3 2]
(2, 3) (3,)
[[12 13 14]
 [18 19 20]]
[[ 8 10 12]
 [14 16 18]]
[[False False False]
 [False False False]]
[]
[ 8 10 12 14]


In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
c = a + b
print(c)
boolean_e = (c < 10)
print(boolean_d)
cFilter = c[c < 15]
print(cFilter)


# index and fancy indexing

In [4]:
import numpy as np
arr = np.array([12,-45,67,89,34,-2,-2,6,-7,8])
print(arr[4]) #indexing
  
ind = [1,4,6] #fancy indexing
print(arr[ind])

print(arr[[1,4,6]])
#slicing in 2 dimensions
print("\n\nslicing")
a = np.array([[1,2,3],[4,5,6]])
print(a[1:2,0:2])


34
[-45  34  -2]
[-45  34  -2]


slicing
[[4 5]]


In [ ]:
# element wise operation
a = np.array([[1,2,3,-4,-7]])
print(np.abs(a))              
              

In [ ]:
print(np.vectorize(5))