In [ ]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))
%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list] 

In [ ]:
import numpy as np
nd_array = np.array([1,2,3,4])
print(nd_array)
print(type(nd_array))

list1 = [2,3,4,5,6]
nd_a = np.array(list1)

print(type(list1))
print(nd_a)

In [1]:
import numpy as np
nd_array = np.array([1,2,3,4])
print(nd_array)
print(type(nd_array))

list1 = [2,3,4,5,6]
nd_a = np.array(list1)
print(type(list1))
print(nd_a)

[1 2 3 4]
<class 'numpy.ndarray'>
<class 'list'>
[2 3 4 5 6]


In [ ]:
zeros = np.zeros([2,2])
print(zeros)

ones = np.ones([3,3])
print(ones)

empty = np.empty([3,3,])
print(empty)

ranges = np.arange(10)
print(ranges)

In [ ]:
n_a = np.zeros([1,2,3,4,])
print(n_a)           # 4 dimensions hain

In [ ]:
n_a = np.zeros([3,4])  #3 row 4 coloumn is called initialization
print(n_a)

In [2]:
import numpy as np

list1=[[0,0,0,0],[0,0,0,0],[0,0,0,0]]   # 3 row 4 coloumn (0 initializer ha )  (2 dimension) (1 array mein sub 3 array)
print(list1)
na = np.zeros([3,4])
print(na)

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


0300 8960038 sir anees

0316 2052540 Hamza
0313 1115563 Gulraeez

In [ ]:
na = np.zeros([3,4])
print(na.shape)
print(na.dtype)
print(na.ndim)

In [6]:
import numpy as np


na = np.zeros([3,4])
print(na)
print(na.shape)
print(na.dtype)
print(na.ndim)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)
float64
2


In [6]:
import numpy as np
a = "myn name is usamai am 19 years old"
print(a[:10])
print(len(a))

myn name i
34
